/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.josue.pe.cpresantacion;

import com.josue.pe.cmodelo.TipoDocumento;
import com.josue.pe.cnegocio.TipoDocumentoBO;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Alumno-PB203
 */
public class JpTipoDocumento extends javax.swing.JPanel {
    TipoDocumentoBO tdbo = new TipoDocumentoBO();
    TipoDocumento td = new TipoDocumento();
    String idTipoDocumento;
    
    /**
     * Creates new form JpTipoDocumento
     */
    public JpTipoDocumento() throws SQLException  {
        initComponents();
        listarTipoDocumento();
    }
    
    public void listarTipoDocumento() throws SQLException {
        tdbo.listarTipoDocumento(tablaTipoDocumento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTipoDocumento = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtSigla = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOrden = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel1.setText("CRUD Tipo Documento");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 40, 523, 61));

        tablaTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTipoDocumentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTipoDocumento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 107, -1, 370));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, -1, -1));

        btnModificar.setText("Editar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, -1, -1));

        jLabel3.setText("formulario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setText("Sigla");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        txtEstado.setBackground(new java.awt.Color(255, 255, 255));
        txtEstado.setForeground(new java.awt.Color(51, 102, 255));
        txtEstado.setBorder(null);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 270, 20));

        txtSigla.setBackground(new java.awt.Color(255, 255, 255));
        txtSigla.setForeground(new java.awt.Color(102, 0, 255));
        txtSigla.setBorder(null);
        jPanel1.add(txtSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 270, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 270, 20));

        jLabel8.setText("Estado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 40));

        jLabel9.setText("orden");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));

        txtOrden.setBackground(new java.awt.Color(255, 255, 255));
        txtOrden.setForeground(new java.awt.Color(51, 51, 255));
        txtOrden.setBorder(null);
        jPanel1.add(txtOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 270, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 270, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 270, 20));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 80, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if(valida()){
            td.setNomnbre(txtNombre.getText());
            td.setEstado(txtEstado.getText());
            td.setOrden(Integer.parseInt(txtOrden.getText()));
            td.setSigla(txtSigla.getText());
            tdbo.agregarTipoDocumento(td); 
            JOptionPane.showMessageDialog(null, ": se guardo corectamente");
            listarTipoDocumento();
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed
    public boolean valida(){
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nombre es requerido!");
            return false;
        }else if(txtSigla.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "sigla requerida!");
            return false;
        }else if(txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Estado requerido!");
            return false;
        }else if(txtOrden.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Orden requerida!");
            return false;
        }
        return true;
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtNombre.setText("");
    txtSigla.setText("");
    txtEstado.setText("");
    txtOrden.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tablaTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTipoDocumentoMouseClicked
       int seleccion = tablaTipoDocumento.rowAtPoint(evt.getPoint());
       idTipoDocumento = tablaTipoDocumento.getValueAt(seleccion, 0)+"";    
       txtNombre.setText(tablaTipoDocumento.getValueAt(seleccion, 1)+"");
       txtSigla.setText(tablaTipoDocumento.getValueAt(seleccion, 2)+"");
       txtEstado.setText(tablaTipoDocumento.getValueAt(seleccion, 3)+"");
       txtOrden.setText(tablaTipoDocumento.getValueAt(seleccion, 4)+"");
       
    }//GEN-LAST:event_tablaTipoDocumentoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            TipoDocumento tf = new TipoDocumento();
      tf.setIdTipoDocumento(Integer.parseInt(idTipoDocumento));
      tdbo.elimiarTipoDocumento(tf);
      listarTipoDocumento();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR" + e.getMessage());
        }
     
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            if(valida()){
            td.setIdTipoDocumento(Integer.parseInt(idTipoDocumento));
            td.setNomnbre(txtNombre.getText());
            td.setEstado(txtEstado.getText());
             td.setSigla(txtSigla.getText());
            td.setOrden(Integer.parseInt(txtOrden.getText()));
            tdbo.modificarTipoDocumento(td); 
            listarTipoDocumento();
            JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
            
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tablaTipoDocumento;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOrden;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
